version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/hp-web
#    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
#    - location: /home/ubuntu/www/hp-web-portal-repo/scripts/install_dependencies
#      timeout: 300
#      runas: root
#    - location: scripts/start_server
#      timeout: 300
#      runas: root
  ApplicationStart:
#    - location: /home/ubuntu/www/hp-web-portal-repo/scripts/install_dependencies
#      timeout: 300
#      runas: root
  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
